#!/usr/sbin/nft -f

# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# See "man nftables" for documentation.

flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0;

    # Allow established/related connections.
    ct state {established, related} accept

    # Early drop of invalid connections.
    ct state invalid drop

    # Allow from loopback.
    iifname lo accept

    # Allow icmp.
    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    # Allow ssh.
    tcp dport 22 accept

    # Allow chameleond direct access.
    tcp dport 9992 accept

    # Allow btpeerd direct access.
    tcp dport 8100 accept

    # Reject everything else.
    reject with icmp type port-unreachable
  }
  chain forward {
    type filter hook forward priority 0;

    # Ignore packets for other systems.
    drop
  }
  chain output {
    type filter hook output priority 0;
    # Allow all output.
  }
}
