# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Custom timestamp template with microsecond precision. Example output:
# Jul  2 00:11:16.265984 raspberrypi pulseaudio[1415]: [pulseaudio] ...
template(name="TraditionalWithMicroseconds" type="list") {
    property(name="timestamp" dateFormat="rfc3164")
    constant(value=".")
    property(name="timestamp" dateFormat="subseconds")
    constant(value=" ")
    property(name="hostname")
    constant(value=" ")
    property(name="syslogtag")
    property(name="msg")
    constant(value="\n")
}

daemon.*                    -/var/log/daemon.log;TraditionalWithMicroseconds

*.=info;*.=notice;*.=warn;\
    auth,authpriv.none;\
    cron,daemon.none;\
    mail,news.none          -/var/log/messages;TraditionalWithMicroseconds
