#!/bin/bash
# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### BEGIN INIT INFO
# Provides:          bluetooth_grpc
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start bluetooth_grpc and stop chameleond service before
# Description:       Enable service provided by bluetooth_grpc for remote
#                    controlling the Chameleon board.
### END INIT INFO

DAEMON_NAME='bluetooth_grpc'
CHAMELEOND_SERVICE="chameleond"
DAEMON="/etc/chromiumos/src/platform/chameleon/utils/run_bluetooth_grpc_venv.sh"
DAEMON_USER='root'
PIDFILE="/var/run/${DAEMON_NAME}.pid"
LOGFILE="/var/log/${DAEMON_NAME}_init"

RETRY_PERIOD=1

is_already_running () {
    start-stop-daemon --stop --test --quiet --pidfile "${PIDFILE}"
}

is_chameleon_service_active() {
    systemctl is-active --quiet "${CHAMELEOND_SERVICE}"
    return $?
}

do_start () {
    if is_chameleon_service_active; then
        echo "Service '${CHAMELEOND_SERVICE}' is running."
        echo "Stopping service '${CHAMELEOND_SERVICE}'..."

        if systemctl stop "${CHAMELEOND_SERVICE}"; then
            echo "Service '${CHAMELEOND_SERVICE}' stopped successfully."
        else
            echo "Error: Failed to stop service '${CHAMELEOND_SERVICE}'."
        fi
    else
        echo "Service '${CHAMELEOND_SERVICE}' is not running."
    fi


    if ! is_already_running; then
        start-stop-daemon --start --background --pidfile "${PIDFILE}" \
            --make-pidfile --user "${DAEMON_USER}" --chuid "${DAEMON_USER}" \
            --startas /bin/bash -- \
            -c "exec ${DAEMON} >> ${LOGFILE} 2>&1"
        do_status
    else
        echo "${DAEMON_NAME} is already running."
    fi
}

do_stop () {
    if is_already_running; then
        start-stop-daemon --stop --pidfile "${PIDFILE}" --retry "${RETRY_PERIOD}" --remove-pidfile
    else
        echo "${DAEMON_NAME} is already stopped"
    fi

    if ! is_chameleon_service_active; then
        systemctl start "${CHAMELEOND_SERVICE}"
    fi
}

do_status () {
    is_already_running &&
        echo "${DAEMON_NAME} is running." ||
        echo "${DAEMON_NAME} is not running"
}

case "$1" in
    start|stop|status)
        do_"${1}"
        ;;

    restart)
        do_stop
        do_start
        ;;

    *)
        echo "Usage: /etc/init.d/${DAEMON_NAME} {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
